spring:
  application:
    name: essen-bestellung
  datasource:
    url: jdbc:mysql://localhost:3306/essen_bestellung_db
    username: root
    password: Saint123
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8989
